# Generated by Django 5.2.5 on 2026-07-25 16:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='类型')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('code_fingerprint', models.CharField(blank=True, max_length=16, verbose_name='授权码指纹')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='详情')),
            ],
            options={
                'verbose_name': '安全事件',
                'verbose_name_plural': '安全事件',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('source_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='源文件路径摘要')),
                ('source_path', models.TextField(verbose_name='源文件路径')),
                ('source_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('source_mtime_ns', models.BigIntegerField(default=0, verbose_name='修改时间戳')),
                ('stable_scan_count', models.PositiveSmallIntegerField(default=0, verbose_name='稳定扫描次数')),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='时长（秒）')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度')),
                ('codec', models.CharField(blank=True, max_length=64, verbose_name='视频编码')),
                ('hls_relative_path', models.CharField(blank=True, max_length=1024, verbose_name='HLS相对路径')),
                ('processing_status', models.CharField(choices=[('discovered', '等待文件稳定'), ('queued', '等待转码'), ('processing', '正在转码'), ('ready', '可播放'), ('failed', '处理失败'), ('missing', '源文件缺失')], default='discovered', max_length=20, verbose_name='处理状态')),
                ('processing_error', models.TextField(blank=True, verbose_name='处理错误')),
                ('sharing_enabled', models.BooleanField(default=False, verbose_name='允许共享')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后扫描时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_digest', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='授权码摘要')),
                ('code_hint', models.CharField(max_length=4, verbose_name='授权码尾号')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('expires_at', models.DateTimeField(verbose_name='失效时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_codes', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '授权码',
                'verbose_name_plural': '授权码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.CharField(max_length=64)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '管理员审计',
                'verbose_name_plural': '管理员审计',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('active', '有效'), ('revoked', '已撤销'), ('ended', '已结束')], default='active', max_length=10)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('max_position_seconds', models.PositiveIntegerField(default=0)),
                ('access_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='videos.accesscode')),
            ],
            options={
                'verbose_name': '播放会话',
                'verbose_name_plural': '播放会话',
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('authorized', '授权成功'), ('start', '开始播放'), ('heartbeat', '播放心跳'), ('pause', '暂停'), ('seek', '拖动'), ('ended', '播放结束'), ('denied', '访问拒绝')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('position_seconds', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='videos.playbacksession')),
            ],
            options={
                'verbose_name': '观看事件',
                'verbose_name_plural': '观看事件',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='playbacksession',
            index=models.Index(fields=['access_code', 'authorized_at'], name='videos_play_access__f36569_idx'),
        ),
        migrations.AddIndex(
            model_name='accesscode',
            index=models.Index(fields=['video', 'enabled', 'expires_at'], name='videos_acce_video_i_8f13bc_idx'),
        ),
    ]
