# Generated by Django 5.2.5 on 2026-07-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_systemsettings_ip_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='code_ciphertext',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='授权码密文'),
        ),
    ]
