# Generated by Django 5.2.5 on 2026-07-30 02:42

from django.db import migrations, models


def populate_active_digests(apps, schema_editor):
    AccessCode = apps.get_model("videos", "AccessCode")
    AccessCode.objects.filter(deleted_at__isnull=True).update(
        active_digest=models.F("code_digest")
    )


def clear_active_digests(apps, schema_editor):
    AccessCode = apps.get_model("videos", "AccessCode")
    AccessCode.objects.update(active_digest=None)


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_accesscode_code_ciphertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='active_digest',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='有效授权码摘要'),
        ),
        migrations.RunPython(
            populate_active_digests,
            clear_active_digests,
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='code_digest',
            field=models.CharField(db_index=True, max_length=64, verbose_name='授权码摘要'),
        ),
    ]
