# Generated by Django 5.2.5 on 2026-07-29 02:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='聊天室名称')),
                ('code_digest', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='授权码摘要')),
                ('code_hint', models.CharField(max_length=4, verbose_name='授权码尾号')),
                ('is_active', models.BooleanField(default=True, verbose_name='开放')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '聊天室',
                'verbose_name_plural': '聊天室',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(max_length=64, verbose_name='会话令牌摘要')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('display_name', models.CharField(max_length=30, verbose_name='显示名称')),
                ('avatar_seed', models.PositiveIntegerField(verbose_name='头像种子')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='进入时间')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后在线时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.chatroom')),
            ],
            options={
                'verbose_name': '聊天参与者',
                'verbose_name_plural': '聊天参与者',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='消息正文')),
                ('client_nonce', models.UUIDField(verbose_name='客户端消息编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.chatparticipant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['room', 'joined_at'], name='chat_chatpa_room_id_3c8cf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(fields=('room', 'avatar_seed'), name='unique_chat_avatar_per_room'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-id'], name='chat_chatme_room_id_85dfd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('participant', 'client_nonce'), name='unique_chat_message_nonce'),
        ),
    ]
