# Generated by Django 5.2.5 on 2026-07-29 03:34

import chat.nicknames
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='nickname_group',
            field=models.CharField(default=chat.nicknames.default_nickname_group, max_length=40, verbose_name='备用昵称组'),
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(fields=('room', 'display_name'), name='unique_chat_nickname_per_room'),
        ),
    ]
