# Generated by Django 5.2.5 on 2026-07-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_nickname_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='device_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='设备特征摘要'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='identity_digest',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='临时身份摘要'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='code_ciphertext',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='授权码密文'),
        ),
    ]
