# Generated by Django 5.2.5 on 2026-07-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatparticipant_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_content_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='图片类型'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image_height',
            field=models.PositiveIntegerField(default=0, verbose_name='图片高度'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image_relative_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='图片相对路径'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='图片大小'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image_width',
            field=models.PositiveIntegerField(default=0, verbose_name='图片宽度'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='消息正文'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('body', ''), _negated=True), models.Q(('image_relative_path', ''), _negated=True), _connector='OR'), name='chat_message_has_content'),
        ),
    ]
