name: tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  django:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - run: pip install -r requirements.txt
      - run: python manage.py check
      - run: python manage.py makemigrations --check --dry-run
      - run: python manage.py test -v 2
